array_width = 60
chain_width = 50
edition = "2024"
fn_call_width = 30
fn_params_layout = "Vertical"
hard_tabs = true
imports_layout = "Vertical"
# indent_style = "Visual"
max_width = 120
newline_style = "Unix"
# struct_field_align_threshold = 100
